/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  async redirects() {
    // Friendly aliases / legacy paths → canonical routes. Keeps bookmarks,
    // typed URLs and demo links working even after pages were renamed.
    const map = [
      ["/home", "/"],
      ["/dashboard", "/"],
      ["/overview", "/"],
      ["/general-ledger", "/journal"],
      ["/ledger", "/journal"],
      ["/gl", "/journal"],
      ["/vouchers", "/journal-entries"],
      ["/accounts", "/chart-of-accounts"],
      ["/coa", "/chart-of-accounts"],
      ["/reports", "/reports/profit-loss"],
      ["/reports/pnl", "/reports/profit-loss"],
      ["/pnl", "/reports/profit-loss"],
      ["/profit-loss", "/reports/profit-loss"],
      ["/p-and-l", "/reports/profit-loss"],
      ["/balance-sheet", "/reports/balance-sheet"],
      ["/bs", "/reports/balance-sheet"],
      ["/cash-flow", "/reports/cash-flow"],
      ["/explorer", "/reports/explorer"],
      ["/sales", "/orders"],
      ["/sales-orders", "/orders"],
      ["/invoices", "/invoicing"],
      ["/billing", "/invoicing"],
      ["/engagements", "/projects"],
      ["/matters", "/projects"],
      ["/timesheet", "/timesheets"],
      ["/people-directory", "/people"],
      ["/directory", "/people"],
      ["/employees", "/people"],
      ["/team", "/people"],
      ["/gst", "/tax"],
      ["/tds", "/tax"],
      ["/compliance", "/tax"],
      ["/recruitment", "/cv-bank"],
      ["/candidates", "/cv-bank"],
      ["/hiring", "/cv-bank"],
      ["/vendor", "/vendors"],
      ["/suppliers", "/vendors"],
      ["/bank", "/banking"],
      ["/reconciliation", "/banking"],
      ["/recon", "/banking"],
      ["/budget", "/planning/budget"],
      ["/forecast", "/planning/budget"],
      ["/business-plan", "/planning/business-plan"],
      ["/cost-audit", "/analysis/cost-audit"],
      ["/intercompany", "/group/intercompany"],
      ["/integrations", "/connections"],
      ["/access", "/setup"],
      ["/admin", "/setup"],
      ["/profile", "/portal"],
      ["/me", "/portal"],
    ];
    return map.map(([source, destination]) => ({ source, destination, permanent: false }));
  },
};

export default nextConfig;
