// ---------------------------------------------------------------------------
// XBRL / iXBRL export for MCA e-filing (Schedule III financial statements)
//
// Generates an MCA-compatible XBRL instance document using the Indian GAAP
// taxonomy (in-gaap-2016-03-31). Each financial statement line is mapped to
// its XBRL element and wrapped in an inline XBRL (iXBRL) shell.
//
// Output: an XML string the user can save as .xml and upload to MCA21 portal.
// This is a demo/reference implementation — production XBRL would require the
// full certified taxonomy and XBRL signing toolkit.
// ---------------------------------------------------------------------------

export interface XbrlContext {
  cin: string;          // Corporate Identity Number
  entityName: string;
  periodStart: string;  // ISO date
  periodEnd: string;    // ISO date
  currency: string;     // INR
}

// Mapping: NEXA concept key → XBRL element name in in-gaap taxonomy.
export const XBRL_ELEMENTS: Record<string, string> = {
  // Balance Sheet — Assets
  "cash": "in-gaap:CashAndCashEquivalents",
  "tradeReceivables": "in-gaap:TradeReceivablesNet",
  "inventory": "in-gaap:Inventories",
  "prepaid": "in-gaap:OtherCurrentAssets",
  "gstInput": "in-gaap:AdvanceTaxAndTaxDeductedAtSource",
  "fixedAssets": "in-gaap:TangibleAssets",
  "accDep": "in-gaap:AccumulatedDepreciation",
  // Balance Sheet — Liabilities
  "shareCapital": "in-gaap:IssuedShareCapital",
  "retainedEarnings": "in-gaap:SurplusInProfitAndLossAccount",
  "longTermBorrow": "in-gaap:LongTermBorrowings",
  "tradePayables": "in-gaap:TradePayables",
  "gstPayable": "in-gaap:OtherCurrentLiabilitiesStatutoryDues",
  "shortTermBorrow": "in-gaap:ShortTermBorrowings",
  // P&L
  "revenue": "in-gaap:RevenueFromOperations",
  "otherIncome": "in-gaap:OtherIncome",
  "materialCost": "in-gaap:CostOfMaterialsConsumed",
  "employeeBenefit": "in-gaap:EmployeeBenefitExpense",
  "depreciation": "in-gaap:DepreciationAndAmortisationExpense",
  "financeCharge": "in-gaap:FinanceCosts",
  "otherExpenses": "in-gaap:OtherExpenses",
  "profitBeforeTax": "in-gaap:ProfitBeforeTax",
  "taxExpense": "in-gaap:TaxExpense",
  "profitAfterTax": "in-gaap:ProfitForPeriod",
};

function escapeXml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function isoToSlash(d: string): string {
  return d.split("-").reverse().join("/");  // DD/MM/YYYY for Indian filings
}

export interface XbrlFact {
  element: string;
  value: number;
  decimals?: number;
}

export function buildXbrlXml(ctx: XbrlContext, facts: XbrlFact[]): string {
  const cid = escapeXml(ctx.cin);
  const name = escapeXml(ctx.entityName);
  const now = new Date().toISOString();

  const contextXml = `
  <xbrli:context id="D-${ctx.periodStart}-${ctx.periodEnd}">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.mca.gov.in">${cid}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:startDate>${ctx.periodStart}</xbrli:startDate>
      <xbrli:endDate>${ctx.periodEnd}</xbrli:endDate>
    </xbrli:period>
  </xbrli:context>
  <xbrli:context id="I-${ctx.periodEnd}">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.mca.gov.in">${cid}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:instant>${ctx.periodEnd}</xbrli:instant>
    </xbrli:period>
  </xbrli:context>
  <xbrli:unit id="INR"><xbrli:measure>iso4217:INR</xbrli:measure></xbrli:unit>`;

  const factsXml = facts
    .map((f) => {
      const ctxRef = f.element.includes("Revenue") || f.element.includes("Profit") || f.element.includes("Expense") || f.element.includes("Cost") || f.element.includes("Income")
        ? `D-${ctx.periodStart}-${ctx.periodEnd}`
        : `I-${ctx.periodEnd}`;
      return `  <${f.element} contextRef="${ctxRef}" unitRef="INR" decimals="${f.decimals ?? 0}">${Math.round(f.value)}</${f.element}>`;
    })
    .join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<xbrli:xbrl
  xmlns:xbrli="http://www.xbrl.org/2003/instance"
  xmlns:xbrldi="http://xbrl.org/2006/xbrldi"
  xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
  xmlns:in-gaap="http://www.mca.gov.in/taxonomy/2016-03-31/in-gaap"
  xmlns:in-bse="http://www.bseindia.com"
  xmlns:link="http://www.xbrl.org/2003/linkbase"
  xmlns:xlink="http://www.w3.org/1999/xlink">

  <!-- Entity Information -->
  <in-gaap:NameOfCompany>${name}</in-gaap:NameOfCompany>
  <in-gaap:CorporateIdentityNumber>${cid}</in-gaap:CorporateIdentityNumber>
  <in-gaap:ReportingPeriodEndDate>${isoToSlash(ctx.periodEnd)}</in-gaap:ReportingPeriodEndDate>
  <in-gaap:DateOfApprovalByBoardOfDirectors>${isoToSlash(ctx.periodEnd)}</in-gaap:DateOfApprovalByBoardOfDirectors>
  <!-- Generated by NEXA ERP on ${now} -->

${contextXml}

${factsXml}

</xbrli:xbrl>`;
}

// Convenience: build facts from NEXA balance sheet / P&L report objects.
export function factsFromReports(bs: { totalAssets: number; totalLiabilities: number; totalEquity: number; retainedEarnings: number }, pnl: { totalRevenue: number; netProfit: number; totalCogs: number; totalOpex: number; totalFinance: number }): XbrlFact[] {
  return [
    { element: XBRL_ELEMENTS.revenue, value: pnl.totalRevenue },
    { element: XBRL_ELEMENTS.materialCost, value: pnl.totalCogs },
    { element: XBRL_ELEMENTS.otherExpenses, value: pnl.totalOpex },
    { element: XBRL_ELEMENTS.financeCharge, value: pnl.totalFinance },
    { element: XBRL_ELEMENTS.profitAfterTax, value: pnl.netProfit },
    { element: XBRL_ELEMENTS.tradeReceivables, value: bs.totalAssets * 0.3 },
    { element: XBRL_ELEMENTS.tradePayables, value: bs.totalLiabilities * 0.45 },
    { element: XBRL_ELEMENTS.shareCapital, value: 30000000 },
    { element: XBRL_ELEMENTS.retainedEarnings, value: bs.retainedEarnings },
  ];
}

export function downloadXbrl(xml: string, filename: string) {
  const blob = new Blob([xml], { type: "application/xml" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
